name: Vacuum OpenAPI Spec linter
description: This is an OpenAPI spec linter using vacuum.
inputs:
  cmd:
    description: "Vacuum command, see https://quobix.com/vacuum/"
    required: true

runs:
  using: "composite"
  steps:
    - name: Install Vacuum
      run: curl -fsSL https://quobix.com/scripts/install_vacuum.sh | sh > /dev/null
      shell: bash
    - name: Run OpenAPI Linter
      run: |
        ${{ inputs.cmd }}
      shell: bash